require 'support/fixtures/data.rb'

require 'support/page_drivers/home.rb'
require 'support/page_drivers/address.rb'
require 'support/page_drivers/cart.rb'
require 'support/page_drivers/complete.rb'
require 'support/page_drivers/confirm.rb'
require 'support/page_drivers/delivery.rb'
require 'support/page_drivers/payment.rb'
require 'support/page_drivers/product.rb'
require 'support/page_drivers/registration.rb'

require 'support/page_drivers/admin/order_menu.rb'

require 'support/page_drivers/admin/login.rb'
require 'support/page_drivers/admin/logs.rb'
require 'support/page_drivers/admin/new_payment.rb'
require 'support/page_drivers/admin/payment.rb'
require 'support/page_drivers/admin/payments.rb'
require 'support/page_drivers/admin/order.rb'
require 'support/page_drivers/admin/orders.rb'
require 'support/page_drivers/admin/customer.rb'
require 'support/page_drivers/admin/promotion.rb'
require 'support/page_drivers/admin/promotions.rb'
require 'support/page_drivers/admin/new_promotion.rb'

require 'support/workflow_driver/process.rb'
